#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Polkit
/usr/libexec/polkit-mate-authentication-agent-1 &

bspc monitor -d I II III IV V VI

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          7
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a kitty desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
# bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#4b7f7b"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
xrandr --output eDP --scale 1.25x1.25 &
# Bar
polybar &
# Notifications
/usr/bin/dunst &
flameshot &
xss-lock --transfer-sleep-lock -- i3lock --nofork &
/usr/libexec/polkit-mate-authentication-agent-1 &
# Wallpaper
feh --bg-center ~/Pictures/wall/ &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Network Applet
nm-applet &
picom --config ~/.config/picom/picom.conf &
# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

